spring:
  application:
    name: inventory

  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:5432/inventory_db}
    username: ${INVENTORY_DB_USER:inventory_user}
    password: ${INVENTORY_DB_PASSWORD:inventory_password}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html